export const News = [
  {
    id: "1",
    img: require("../components/images/Section/president-barack-obama-pete-souza.jpg"),
    head: "Understanding Long Covid",
    title: "We know more now than before, and it’s still alarming",
    date: "Nov 25, 2022",
    isTrending: false,
    category: "",
    key: "Long Covid",
    read: "9 min read",
    createdUser: {
      Name: "Dr. Tom Frieden",
      userId: "1",
      img: require("../components/images/Section/img_forest.jpeg"),
    },
  },
  {
    id: "2",
    img: require("../components/images/Section/president-barack-obama-pete-souza.jpg"),
    head: "Braiding Past into Future",
    title: "Nican Huehcatlahtolli, a New Futurism",
    date: "Nov 25, 2022",
    isTrending: true,
    category: "",
    key: "Futurism",
    read: "11 min read",
    createdUser: {
      Name: "David Bowles",
      userId: "2",
      img: require("../components/images/Section/img_forest.jpeg"),
    },
  },
  {
    id: "3",
    img: require("../components/images/Section/president-barack-obama-pete-souza.jpg"),
    head: "Learning to Cope with Estrangement: When Children “Cancel” Their Parents",
    title:
      "An estranged father reflects on the stigma and surprising prevalence of these family rifts.",
    date: "Aug 21, 2022",
    isTrending: true,
    category: "",
    key: "Parental Alienation",
    read: "6 min read",
    createdUser: {
      Name: "Ed Erginziger",
      userId: "3",
      img: require("../components/images/Section/img_forest.jpeg"),
    },
  },

  {
    id: "4",
    img: require("../components/images/Section/president-barack-obama-pete-souza.jpg"),
    head: "ChatGPT Is Having a Thomas Edison Moment",
    title: "Why breakthrough technologies need to be accessible",
    date: "Dec  8, 2022",
    isTrending: false,
    category: "",
    key: "Gpt 3",
    read: "4 min read",
    createdUser: {
      Name: "Thomas Smith",
      userId: "4",
      img: require("../components/images/Section/img_forest.jpeg"),
    },
  },
  {
    id: "5",
    img: require("../components/images/Section/president-barack-obama-pete-souza.jpg"),
    head: " Spotify’s Year-End Lists Are the Ultimate Personality Test",
    title:
      "Why the mass sharing of the music streaming service’s year-end lists is uniquely telling",
    date: "Dec 6, 2022",
    isTrending: false,
    category: "",
    key: "Music",
    read: "3 min read",
    createdUser: {
      Name: "Allegra Hobbs",
      userId: "5",
      img: require("../components/images/Section/img_forest.jpeg"),
    },
  },
];

export const Lists = [
  {
    num: "01",
    img: require("./images/Section/download.jpeg"),
    ner: "Tom Cooper",
    title: "Ukraine War, 13 January 2023",
    date: "Jan 13 . 7 min read",
  },
  {
    num: "02",
    img: require("./images/Section/download.jpeg"),
    ner: "Tony Stubblebine in 3 Min Read",
    title: "Medium embraces Mastodon",
    date: "Jan 12 . 3 min read",
  },
  {
    num: "03",
    img: require("./images/Section/download.jpeg"),
    ner: "Owen Jones",
    title: "Thoughts on my Dad and Death, 5 years on",
    date: "Jan 14 . 3 min read",
  },
  {
    num: "04",
    img: require("./images/Section/download.jpeg"),
    ner: "Umair Haque in Eudational and Co",
    title: "Britain's Finally Figuring Out Brexit",
    date: "Jan 3 . 11 min read",
  },
  {
    num: "05",
    img: require("./images/Section/download.jpeg"),
    ner: "Will Lockett",
    title: "Tesla Is in Immense Trouble and Musk Knows It",
    date: "Jan 10 . 4 min read",
  },
  {
    num: "06",
    img: require("./images/Section/download.jpeg"),
    ner: "Ukraine War",
    title: "What You Probably Don't know About Your Pastor When He Preaches",
    date: "Jan 4 . 5 min read",
  },
];
